# Generated by Django 3.2.9 on 2021-11-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='heading',
            new_name='title',
        ),
    ]
