# Generated by Django 3.2.9 on 2021-12-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_date_view_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('publication_date', models.DateField()),
                ('view_num', models.IntegerField(default=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
