# Generated by Django 3.2.9 on 2021-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211203_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('creation_date', models.DateField()),
                ('view_num', models.IntegerField(default=6)),
            ],
        ),
        migrations.DeleteModel(
            name='All_list',
        ),
    ]
