# Generated by Django 3.2.9 on 2021-12-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='post_covers/default.png', null=True, upload_to='post_covers/'),
        ),
    ]
